# Generated by Django 5.0.3 on 2024-04-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
